
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Aug 25 12:51:19 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 38;
  public static final int CONST = 25;
  public static final int NUMCONST = 18;
  public static final int SMALLEREQUAL = 16;
  public static final int NOTEQUAL = 12;
  public static final int SMALLER = 15;
  public static final int LPAREN = 31;
  public static final int CONTINUE = 6;
  public static final int MINUS = 40;
  public static final int RPAREN = 32;
  public static final int SEMICOLON = 26;
  public static final int AND = 2;
  public static final int OR = 13;
  public static final int COMMA = 27;
  public static final int CLASS = 33;
  public static final int EQUALEQUAL = 10;
  public static final int DIV = 43;
  public static final int PLUS = 41;
  public static final int IF = 11;
  public static final int DOT = 8;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 39;
  public static final int RETURN = 14;
  public static final int EQUAL = 28;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int MUL = 42;
  public static final int MOD = 44;
  public static final int BREAK = 5;
  public static final int IDENT = 19;
  public static final int BIGGER = 3;
  public static final int VOID = 35;
  public static final int LBRACE = 23;
  public static final int ELSE = 9;
  public static final int LSQUARE = 29;
  public static final int READ = 36;
  public static final int RSQUARE = 30;
  public static final int CHARCONST = 21;
  public static final int WHILE = 17;
  public static final int BIGGEREQUAL = 4;
  public static final int RBRACE = 24;
  public static final int BOOLCONST = 20;
  public static final int EXTENDS = 34;
  public static final int PROG = 22;
  public static final int PRINT = 37;
  public static final int DO = 7;
  public static final int FACTORIAL = 46;
}

